from __future__ import annotations

import random
from typing import TypeVar

from app.models import Equipment, InspectionPlan, InspectionPlanStep
from app.repositories.employee import EmployeeRepository
from app.repositories.equipment import EquipmentRepository
from app.repositories.inspection_plan import UNSET, InspectionPlanRepository
from app.schemas.inspection_plan import (
    InspectionPlanCreate,
    InspectionPlanEquipmentRead,
    InspectionPlanRead,
    InspectionPlanStepRead,
    InspectionPlanUpdate,
)
from app.services.errors import ServiceError

T = TypeVar("T")


class InspectionPlanService:
    _STATUS_PRIORITY = {
        "broken": 0,
        "out_of_service": 0,
        "maintenance": 1,
        "operational": 2,
    }

    def __init__(
        self,
        plan_repository: InspectionPlanRepository,
        equipment_repository: EquipmentRepository,
        employee_repository: EmployeeRepository,
    ) -> None:
        self.plan_repository = plan_repository
        self.equipment_repository = equipment_repository
        self.employee_repository = employee_repository

    async def create(self, payload: InspectionPlanCreate) -> InspectionPlanRead:
        await self._assert_equipment_exists(payload.equipment_ids)
        if payload.employee_id is not None:
            await self._assert_employee_exists(payload.employee_id)

        created = await self.plan_repository.create(
            payload.model_dump(exclude={"equipment_ids", "employee_id"}),
            payload.equipment_ids,
            employee_id=payload.employee_id,
        )
        return await self._to_read_model(created)

    async def generate_for_employee(self, employee_id: int) -> InspectionPlanRead:
        await self._assert_employee_exists(employee_id)

        equipment_items = await self.equipment_repository.list()
        prioritized_equipment_ids = [
            equipment.id
            for equipment in sorted(
                equipment_items,
                key=lambda item: (
                    self._STATUS_PRIORITY.get(item.status, 3),
                    item.id or 0,
                ),
            )
            if equipment.id is not None
        ]

        if not prioritized_equipment_ids:
            raise ServiceError(
                "No equipment found to generate an inspection plan", status_code=400
            )

        created = await self.plan_repository.create(
            {
                "observations": "Auto-generated by status priority",
                "supervisor_follow_up": bool(random.getrandbits(1)),
            },
            prioritized_equipment_ids,
            employee_id=employee_id,
        )
        return await self._to_read_model(created)

    async def get_or_generate_for_employee(
        self, employee_id: int
    ) -> InspectionPlanRead:
        await self._assert_employee_exists(employee_id)

        active_plan = await self.plan_repository.find_active_for_employee(employee_id)
        if active_plan:
            return await self._to_read_model(active_plan)
        return await self.generate_for_employee(employee_id)

    async def list(self) -> list[InspectionPlanRead]:
        items = await self.plan_repository.list()
        return [await self._to_read_model(item) for item in items]

    async def get(self, plan_id: int) -> InspectionPlanRead:
        item = await self.plan_repository.get_by_id(plan_id)
        if not item:
            raise ServiceError("Inspection plan not found", status_code=404)
        return await self._to_read_model(item)

    async def get_next_step(self, plan_id: int) -> InspectionPlanStep | None:
        plan = await self.plan_repository.get_by_id(plan_id)
        if not plan:
            raise ServiceError("Inspection plan not found", status_code=404)
        return await self.plan_repository.get_next_pending_step(plan_id)

    async def update(
        self, plan_id: int, payload: InspectionPlanUpdate
    ) -> InspectionPlanRead:
        current = await self.plan_repository.get_by_id(plan_id)
        if not current:
            raise ServiceError("Inspection plan not found", status_code=404)

        data = payload.model_dump(exclude_unset=True)
        equipment_ids = data.pop("equipment_ids", None)

        employee_id: int | None | object = UNSET
        if "employee_id" in data:
            employee_id = data.pop("employee_id")

        if equipment_ids is not None:
            await self._assert_equipment_exists(equipment_ids)

        if employee_id is not UNSET and employee_id is not None:
            await self._assert_employee_exists(employee_id)

        updated = await self.plan_repository.update(
            plan_id,
            data,
            equipment_ids,
            employee_id=employee_id,
        )
        if not updated:
            raise ServiceError("Inspection plan not found", status_code=404)
        return await self._to_read_model(updated)

    async def delete(self, plan_id: int) -> None:
        deleted = await self.plan_repository.delete(plan_id)
        if not deleted:
            raise ServiceError("Inspection plan not found", status_code=404)

    async def _assert_equipment_exists(self, equipment_ids: list[int]) -> None:
        if not equipment_ids:
            raise ServiceError("At least one equipment_id is required", status_code=400)

        missing_ids = [
            equipment_id
            for equipment_id in equipment_ids
            if not await self.equipment_repository.get_by_id(equipment_id)
        ]
        if missing_ids:
            raise ServiceError(
                f"Unknown equipment ids: {missing_ids}",
                status_code=400,
            )

    async def _assert_employee_exists(self, employee_id: int) -> None:
        if not await self.employee_repository.get_by_id(employee_id):
            raise ServiceError(
                "Employee for inspection plan was not found", status_code=400
            )

    async def _to_read_model(
        self, entity: InspectionPlan | object
    ) -> InspectionPlanRead:
        normalized_entity = self._unwrap_entity(entity, InspectionPlan)
        if normalized_entity is None:
            raise ServiceError("Inspection plan entity is invalid", status_code=500)
        entity = normalized_entity

        if entity.id is None:
            raise ServiceError("Inspection plan ID is missing", status_code=500)

        assigned_employee_id = await self.plan_repository.get_assigned_employee_id(
            entity.id
        )
        next_step = await self.plan_repository.get_next_pending_step(entity.id)

        normalized_steps = [
            step
            for raw_step in entity.steps
            if (step := self._unwrap_entity(raw_step, InspectionPlanStep)) is not None
        ]
        sorted_steps = sorted(normalized_steps, key=lambda step: step.step_order)
        normalized_equipment_items = [
            equipment
            for raw_equipment in entity.equipment_items
            if (equipment := self._unwrap_entity(raw_equipment, Equipment)) is not None
        ]
        equipment_by_id = {
            equipment.id: equipment
            for equipment in normalized_equipment_items
            if equipment.id is not None
        }

        steps_read: list[InspectionPlanStepRead] = []
        ordered_equipment: list[InspectionPlanEquipmentRead] = []

        for step in sorted_steps:
            equipment = self._unwrap_entity(
                step.equipment, Equipment
            ) or equipment_by_id.get(step.equipment_id)
            if not equipment:
                continue

            equipment_read = InspectionPlanEquipmentRead.model_validate(equipment)
            ordered_equipment.append(equipment_read)
            steps_read.append(
                InspectionPlanStepRead(
                    id=step.id or 0,
                    step_order=step.step_order,
                    equipment=equipment_read,
                    completed_at=step.completed_at,
                    completed_inspection_id=step.completed_inspection_id,
                    is_completed=step.completed_at is not None,
                )
            )

        if not ordered_equipment:
            ordered_equipment = [
                InspectionPlanEquipmentRead.model_validate(equipment)
                for equipment in normalized_equipment_items
            ]

        return InspectionPlanRead(
            id=entity.id,
            timestamp=entity.timestamp,
            observations=entity.observations,
            score=entity.score,
            supervisor_follow_up=entity.supervisor_follow_up,
            employee_id=assigned_employee_id,
            equipment_items=ordered_equipment,
            steps=steps_read,
            next_equipment_id=next_step.equipment_id if next_step else None,
            is_completed=next_step is None,
        )

    def _unwrap_entity(self, value: object, expected_type: type[T]) -> T | None:
        if isinstance(value, expected_type):
            return value

        if isinstance(value, tuple):
            for item in value:
                unwrapped = self._unwrap_entity(item, expected_type)
                if unwrapped is not None:
                    return unwrapped

        mapping = getattr(value, "_mapping", None)
        if mapping is not None:
            for item in mapping.values():
                unwrapped = self._unwrap_entity(item, expected_type)
                if unwrapped is not None:
                    return unwrapped

        return None
